### ISSUE TITLE
Leaving this as "button" element is fine

### ISSUE THREAD

**Issue by deletosh** [neimaaman/first-ecommerce-store#5]
See: https://github.com/neimaaman/first-ecommerce-store/blob/0a4d2c7149d04ae0237cf0361aa031f8b7ee8155/index.html#L58-L60

**Comment by neimaaman** [comment]
i am confused on "button" number 58-60 did u say leave it as it is or change it?

**Comment by deletosh** [comment]
@neimaaman please when you send the message, be sure to "@" me so I get the notification.

you can remove the `type="button"` it's not needed.

**Comment by neimaaman** [comment]
@deletosh, thank you!
